---
- name: change server hostname
  hostname:
    name: "{{ inventory_hostname }}"
  become: true

- name: set timezone to "{{ region }}/{{ city }}"
  timezone: 
    name: "{{ region }}/{{ city }}"
  become: true

- name: update apt cache
  apt:
    update_cache: yes
  become: true


- block:
    - name: create a swap file
      shell: fallocate -l {{ swap_size }} /swapfile
      args: 
        creates: /swapfile
      become: true

    - name: set the correct permissions
      file:
        path: "{{ swapfile_path }}"
        owner: root
        group: root
        mode: '0600'
      become: true

    - name: make the file a swap file
      shell: mkswap /swapfile
      when: ansible_facts.swapfree_mb == 0
      become: true

    - name: enable the swap file
      shell: swapon /swapfile
      when: ansible_facts.swapfree_mb == 0
      become: true

    - name: add swap file to fstab
      mount:
        name: none
        src: /swapfile
        fstype: swap
        opts: sw
        passno: 0
        dump: 0
        state: present
      become: true
        
# tasks file for common
