---
- block:
    - name: disable the swap
      shell: swapoff -a
      when: ansible_facts.swaptotal_mb > 0
      become: true
    
    # - name: Get the swapfile path
    #   command: swapon -s | awk 'NR==2 {print $1}'
    #   register: swapfile_path
    #   when: ansible_facts.swaptotal_mb > 0 

    - name: Delete the swapfile
      file:
        state: absent
        path: "{{ swapfile_path }}"
      when: ansible_facts.swaptotal_mb > 0
      become: true
    
    - name: delete swap from fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^{{ swapfile_path }}.*$'
        state: absent
        backup: yes
      become: true
# tasks file for swaptrasher
